name: Lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Needed for Prettier
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          # https://github.com/terraform-linters/tflint/tags
          tflint_version: v0.59.1
          cache: true

      - name: Validate Terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Format Terraform
        run: |
          terraform fmt -recursive -check

      - name: Lint Terraform
        run: |
          tflint --init
          tflint --recursive

      - name: Format markdown and yaml
        run: |
          npx prettier@3.6.2 --check '**/*.{yaml,yml,md}'
